"""
Write a program to generate a Fibonacci series of numbers.
Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
   a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
   b) Generate the series until the element in the series is less than Max number.
"""
i = 0
j = 1

num = int(input("Enter the number you want in fibo. series :"))
print(i)
print(j)
for x in range(2,num):
    j = i+j
    i = j-i
    print(j)


i = 0
j = 1
num = int(input("Enter the max no. for the fibo series :"))
print(i)
print(j)
while i < num:
    j = i+j
    i = j-i
    if j > num: continue
    print(j)
